/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_apprentice_QLog_JNI */

#ifndef _Included_com_example_android_apprentice_QLog_JNI
#define _Included_com_example_android_apprentice_QLog_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_apprentice_QLog_JNI
 * Method:    Qlog_Start
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_android_1apprentice_QLog_1JNI_Qlog_1Start
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
