//
// Created by baoshu.cheng on 2022/4/2.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_apprentice_QLog_JNI */

#ifndef _Included_com_example_android_apprentice_QLog_JNI
#define _Included_com_example_android_apprentice_QLog_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_apprentice_QLog_JNI
 * Method:    Qlog_Start
 * Signature: ()I
 */
char* menu_return(jint type)
{
  char* res_menu;
  switch(type)
  {
      case 1:
        res_menu = "Helloworld Type1";
        break;
      case 2:
        res_menu = "Helloworld Type2";
        break;
    default:
      res_menu = "Helloworld unknow Type";
      break;
  }
  return res_menu;
}

JNIEXPORT jstring JNICALL Java_com_example_android_1apprentice_QLog_1JNI_Qlog_1Start
  (JNIEnv *env, jclass myjclass,jint mytype)
  {
    return (*env)->NewStringUTF(env,menu_return(mytype));
  }

#ifdef __cplusplus
}
#endif
#endif
